// This code was generated by ChatGPT

function setup() {
    createCanvas(400, 400);
    background(220);
    let shapes = drawShapes();
    updateShapes(shapes);
  }
  
  function drawShapes() {
    for (let i = 0; i < 10; i++) {
      let x = random(width);
      let y = random(height);
      let w = random(10, 50);
      let h = random(10, 50);
      let col = color(random(255), random(255), random(255));
      fill(col);
      rect(x, y, w, h);
    }
    return document.querySelectorAll('rect');
  }
  
  function updateShapes(shapes) {
    for (let shape of shapes) {
      let x = parseFloat(shape.getAttribute('x'));
      let y = parseFloat(shape.getAttribute('y'));
      let w = parseFloat(shape.getAttribute('width'));
      let h = parseFloat(shape.getAttribute('height'));
      let col = color(random(255), random(255), random(255));
      fill(col);
      rect(x, y, w, h);
    }
  }
  
  function draw() {
    // Some code here
    let r = 20;
    let x = mouseX;
    let y = mouseY;
    ellipse(x, y, r, r);
  }
  